// resources/js/components/LoginForm.vue
<script setup lang="ts">
import { Form } from '@inertiajs/vue3';
import type { HTMLAttributes } from 'vue';
import InputError from '@/components/InputError.vue';
import PasswordInput from '@/components/PasswordInput.vue';
import TextLink from '@/components/TextLink.vue';
import { Button } from '@/components/ui/button';
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import {
    Field,
    FieldDescription,
    FieldGroup,
    FieldLabel,
} from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Spinner } from '@/components/ui/spinner';
import { cn } from '@/lib/utils';
import { store } from '@/routes/login';
import { request } from '@/routes/password';

const props = defineProps<{
    class?: HTMLAttributes['class'];
    canResetPassword?: boolean;
    status?: string;
}>();
</script>

<template>
    <div :class="cn('flex flex-col gap-6', props.class)">
        <Card
            class="rounded-2xl border-zinc-800 bg-zinc-900/90 text-white shadow-2xl backdrop-blur-xl"
        >
            <CardHeader class="space-y-1.5 px-6 pt-6 pb-2 text-left">
                <CardTitle
                    class="font-display text-xl font-bold tracking-tight text-white"
                >
                    Masuk ke Akun Anda
                </CardTitle>
                <CardDescription class="text-xs leading-relaxed text-zinc-400">
                    Masukkan Email atau 16 Digit NIK dan password Anda untuk
                    melanjutkan
                </CardDescription>
            </CardHeader>
            <CardContent class="px-6 py-5">
                <div
                    v-if="status"
                    class="mb-4 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-center text-xs font-semibold text-emerald-400"
                >
                    {{ status }}
                </div>

                <Form
                    v-bind="store.form()"
                    :reset-on-success="['password']"
                    v-slot="{ errors, processing }"
                >
                    <FieldGroup>
                        <Field>
                            <FieldLabel
                                for="email"
                                class="text-xs font-medium text-zinc-300"
                            >
                                Email atau NIK
                            </FieldLabel>
                            <Input
                                id="email"
                                type="text"
                                name="email"
                                required
                                autofocus
                                :tabindex="1"
                                autocomplete="username"
                                placeholder="email@example.com atau 16 digit NIK"
                                class="h-10 rounded-xl border-zinc-700 bg-zinc-950 px-3.5 text-sm text-white placeholder-zinc-500 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
                            />
                            <InputError :message="errors.email" />
                        </Field>

                        <Field>
                            <div class="flex items-center justify-between">
                                <FieldLabel
                                    for="password"
                                    class="text-xs font-medium text-zinc-300"
                                >
                                    Password
                                </FieldLabel>
                                <TextLink
                                    v-if="canResetPassword"
                                    :href="request()"
                                    class="text-xs text-indigo-400 transition-colors hover:text-white"
                                    :tabindex="5"
                                >
                                    Lupa password?
                                </TextLink>
                            </div>
                            <PasswordInput
                                id="password"
                                name="password"
                                required
                                :tabindex="2"
                                autocomplete="current-password"
                                placeholder="Masukkan Password"
                                class="h-10 rounded-xl border-zinc-700 bg-zinc-950 px-3.5 text-sm text-white placeholder-zinc-500 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
                            />
                            <InputError :message="errors.password" />
                        </Field>

                        <Field>
                            <div
                                class="flex items-center justify-between pt-0.5"
                            >
                                <FieldLabel
                                    for="remember"
                                    class="flex cursor-pointer items-center space-x-2 text-xs font-normal text-zinc-400 hover:text-zinc-200"
                                >
                                    <Checkbox
                                        id="remember"
                                        name="remember"
                                        :tabindex="3"
                                    />
                                    <span>Ingat saya</span>
                                </FieldLabel>
                            </div>
                        </Field>

                        <Field>
                            <Button
                                type="submit"
                                class="h-10 w-full cursor-pointer rounded-xl bg-linear-to-r from-indigo-500 to-pink-500 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition-all duration-300 hover:opacity-90 disabled:opacity-50"
                                :tabindex="4"
                                :disabled="processing"
                                data-test="login-button"
                            >
                                <Spinner
                                    v-if="processing"
                                    class="mr-2 h-4 w-4 text-white"
                                />
                                <span>Masuk ke Sistem</span>
                            </Button>
                            <Button
                                variant="outline"
                                type="button"
                                class="h-10 w-full rounded-xl border-zinc-700 bg-transparent text-xs font-medium text-zinc-300 transition-colors hover:bg-zinc-800 hover:text-white"
                            >
                                Masuk dengan Google
                            </Button>
                            <FieldDescription
                                class="mt-2 text-center text-xs text-zinc-400"
                            >
                                Belum punya akun?
                                <a
                                    href="#"
                                    class="font-medium text-white underline underline-offset-4 hover:text-indigo-400"
                                >
                                    Hubungi Admin
                                </a>
                            </FieldDescription>
                        </Field>
                    </FieldGroup>
                </Form>
            </CardContent>
        </Card>
    </div>
</template>

// src/presentation/components/auth/login_form.tsx
import { Link } from 'react-router-dom';
import { User as UserIcon, Lock, Eye, EyeOff, AlertCircle } from 'lucide-react';
import type { FormEvent } from 'react';

interface LoginFormProps {
  identifier: string;
  password: string;
  showPassword: boolean;
  identifierError: string;
  passwordError: string;
  generalError: string;
  isLoading: boolean;
  onIdentifierChange: (value: string) => void;
  onPasswordChange: (value: string) => void;
  onTogglePassword: () => void;
  onSubmit: (e: FormEvent) => void;
}

export function LoginForm({
  identifier,
  password,
  showPassword,
  identifierError,
  passwordError,
  generalError,
  isLoading,
  onIdentifierChange,
  onPasswordChange,
  onTogglePassword,
  onSubmit,
}: LoginFormProps) {
  return (
    <div className="bg-white rounded-2xl shadow-xl shadow-slate-200/50 p-6 border border-slate-100">
      <div className="mb-4">
        <h2 className="text-2xl font-urbanist font-bold text-gray-900">
          Masuk ke Dashboard
        </h2>
        <p className="mt-1 text-gray-500">
          Gunakan email atau NIK untuk masuk
        </p>
      </div>

      {/* Error message */}
      {generalError && (
        <div className="mb-4 p-3 rounded-xl bg-red-50 border border-red-100 flex items-center gap-2 text-red-600">
          <AlertCircle className="w-5 h-5 shrink-0" />
          <span className="text-sm">{generalError}</span>
        </div>
      )}

      {/* Login Form */}
      <form onSubmit={onSubmit} className="space-y-4">
        {/* Identifier field */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">
            Email atau NIK
          </label>
          <div className="relative">
            <UserIcon className="absolute left-3.5 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              value={identifier}
              onChange={(e) => onIdentifierChange(e.target.value)}
              className={`w-full pl-11 pr-4 py-2 text-sm rounded-xl border ${identifierError ? 'border-red-300 focus:border-red-500' : 'border-slate-200 focus:border-blue-500'} bg-slate-50 focus:bg-white outline-none transition-all`}
              placeholder="Masukkan email atau NIK"
              disabled={isLoading}
            />
          </div>
          {identifierError && (
            <p className="mt-1.5 text-sm text-red-500">{identifierError}</p>
          )}
        </div>

        {/* Password field */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">
            Password
          </label>
          <div className="relative">
            <Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type={showPassword ? 'text' : 'password'}
              value={password}
              onChange={(e) => onPasswordChange(e.target.value)}
              className={`w-full pl-11 pr-11 text-sm py-2 rounded-xl border ${passwordError ? 'border-red-300 focus:border-red-500' : 'border-slate-200 focus:border-blue-500'} bg-slate-50 focus:bg-white outline-none transition-all`}
              placeholder="Masukkan password"
              disabled={isLoading}
            />
            <button
              type="button"
              onClick={onTogglePassword}
              className="absolute right-3.5 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
            >
              {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
            </button>
          </div>
          {passwordError && (
            <p className="mt-1.5 text-sm text-red-500">{passwordError}</p>
          )}
        </div>

        {/* Submit button */}
        <button
          type="submit"
          disabled={isLoading}
          className="w-full py-2 px-4 bg-linear-to-r from-slate-800 to-slate-900 text-white font-medium rounded-xl hover:from-slate-700 hover:to-slate-800 focus:ring-4 focus:ring-slate-500/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 shadow-lg shadow-slate-300"
        >
          {isLoading ? 'Memproses...' : 'Masuk'}
        </button>
      </form>

      {/* Register link */}
      <p className="mt-6 text-center text-sm text-gray-600">
        Belum punya akun?{' '}
        <Link to="/register" className="text-blue-600 hover:text-blue-700 font-medium">
          Daftar
        </Link>
      </p>
    </div>
  );
}
