// src/presentation/components/common/EmptyState.tsx
/**
 * EmptyState Component
 * Reusable empty state display for lists and search results
 */

import type { LucideIcon } from 'lucide-react';
import { FileText, Users, UserX, Search } from 'lucide-react';

type EmptyStateType = 'no-data' | 'not-found' | 'search' | 'custom';

interface Props {
    type?: EmptyStateType;
    icon?: LucideIcon;
    title: string;
    description?: string;
}

const defaultIcons: Record<EmptyStateType, LucideIcon> = {
    'no-data': Users,
    'not-found': UserX,
    'search': Search,
    'custom': FileText,
};

export function EmptyState({ type = 'custom', icon, title, description }: Props) {
    const Icon = icon || defaultIcons[type];

    return (
        <div className="py-12 text-center">
            <div className="w-14 h-14 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Icon className="w-7 h-7 text-gray-400" />
            </div>
            <h4 className="font-medium text-gray-900 mb-1">{title}</h4>
            {description && (
                <p className="text-gray-500 text-sm">{description}</p>
            )}
        </div>
    );
}

// resources/js/components/EmptyState.vue
<script setup lang="ts">
import type { Component, HTMLAttributes } from 'vue';
import { cn } from '@/lib/utils';

type Props = {
    class?: HTMLAttributes['class'];
    icon?: Component;
    title?: string;
    description?: string;
};

const props = defineProps<Props>();
</script>

<template>
    <div
        :class="
            cn(
                'flex h-full min-h-64 flex-col items-center justify-center gap-3 rounded-xl border border-dashed border-border p-8 text-center',
                props.class,
            )
        "
    >
        <div
            v-if="icon || $slots.icon"
            class="flex h-12 w-12 items-center justify-center rounded-full bg-muted"
        >
            <slot name="icon">
                <component
                    :is="icon"
                    v-if="icon"
                    class="h-6 w-6 text-muted-foreground"
                />
            </slot>
        </div>

        <div class="space-y-1">
            <p
                v-if="title || $slots.title"
                class="text-sm font-medium text-foreground"
            >
                <slot name="title">{{ title }}</slot>
            </p>
            <p
                v-if="description || $slots.description"
                class="text-xs text-muted-foreground"
            >
                <slot name="description">{{ description }}</slot>
            </p>
        </div>

        <div v-if="$slots.default" class="mt-1">
            <slot />
        </div>
    </div>
</template>
